name: sleek_http_client
description: A sleek, pure-Dart HTTP client with connectivity checking, token refresh, multipart support, and structured logging.
version: 1.1.1
repository: https://github.com/IcySunStudio/sleek_http_client
issue_tracker: https://github.com/IcySunStudio/sleek_http_client/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.6.0
  connectivity_plus: ^7.1.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
